# Statistical Analysis in Typhus Dataset

## Imports

Libraries to be used.

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

## Datasets

Directory where the files to be used are located and the name of the files.

In [2]:
directory = '/home/abraham/Documents/Python/Notebooks/'
file = 'dataset.csv'
filepath = directory + file

Once we have the file path we load the files as dataframes.

In [3]:
df_patients   = pd.read_csv(filepath)
df_patients

,MRN,Age (years),Gender,Epidemiologic link to SARS-CoV-2,FEVER fever before hospital,FEVER Tmax xxx or greater until next degree,Lowest systolic BP in ED (within first two hours of presentation),Lowest diastolic BP in ED (within first two hours of presentation),Highest heart rate in ED (within first two hours of presentation),Antecedent Illness,...,"Platelets, admission","AST, admission","ALT, admission","Sodium, admission","Troponin, admission","BNP, admission","Fibrinogen, admission",LDH,PATIENT HAD TYPHUS?,PATIENT HAD MISC?
0,FRHQ53971,17.0,Female,Yes,10.0,105.0,75.0,39.0,116.0,No,...,385.0,101.0,53.0,133.0,2.446,323.6,772.0,802.0,No,Yes
1,ZWZJ23529,15.0,Female,Yes,6.0,103.0,91.0,42.0,115.0,Yes,...,203.0,22.0,20.0,139.0,0.010,518.0,704.0,565.0,No,Yes
2,SDBJ73753,5.0,Male,No,5.0,103.0,95.0,53.0,120.0,No,...,400.0,41.0,16.0,137.0,0.010,43.7,577.0,875.0,No,Yes
3,JLFE85476,5.0,Male,No,5.0,104.0,106.0,58.0,116.0,No,...,126.0,42.0,18.0,128.0,0.010,16.2,546.0,684.0,No,Yes
4,GCKX65582,10.0,Female,Yes,5.0,103.0,91.0,53.0,154.0,No,...,150.0,70.0,50.0,135.0,0.030,NaN,489.0,956.0,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,KBXJ26432,17.0,Male,No,9.0,103.0,110.0,52.0,99.0,No,...,66.0,424.0,305.0,131.0,0.062,68.4,247.0,820.0,Yes,No
216,BRHO87324,9.0,Female,No,6.0,103.0,115.0,57.0,129.0,No,...,143.0,80.0,80.0,136.0,0.010,10.0,494.0,469.0,Yes,No
217,QWKZ64663,12.0,Female,No,14.0,102.0,117.0,66.0,112.0,No,...,332.0,33.0,45.0,138.0,NaN,NaN,NaN,414.0,Yes,No
218,FEYH27707,6.0,Male,No,8.0,102.0,84.0,53.0,92.0,No,...,143.0,89.0,52.0,135.0,0.010,10.0,389.0,548.0,Yes,No
219,PHPJ24161,16.0,Female,No,7.0,103.0,110.0,67.0,137.0,No,...,182.0,102.0,60.0,135.0,0.010,10.0,328.0,640.0,Yes,No

In [4]:
columns = df_patients.columns.to_list()

In [5]:
columns.remove('MRN')
columns.remove('PATIENT HAD TYPHUS?')
columns.remove('PATIENT HAD MISC?')

In [10]:
df_analysis = pd.DataFrame(columns=['Feature', 'Male', 'Female', 'Median', 'IQR1', 'IQR3', 'Yes'])
for column in columns:
    feature_typhus = column + ' - Typhus'
    feature_misc = column + ' - MIS-C'
    
    typhus_male = np.nan
    typhus_female = np.nan
    misc_male = np.nan
    misc_female = np.nan
    typhus_yes = np.nan
    misc_yes = np.nan
    typhus_median = np.nan
    typhus_iqr1 = np.nan
    typhus_iqr3 = np.nan
    misc_median = np.nan
    misc_iqr1 = np.nan
    misc_iqr3 = np.nan
    
    if column == 'Gender':
        typhus_male = df_patients['Gender'].loc[(df_patients['PATIENT HAD TYPHUS?']=='Yes')&(df_patients['Gender']=='Male')].value_counts()
        typhus_female = df_patients['Gender'].loc[(df_patients['PATIENT HAD TYPHUS?']=='Yes')&(df_patients['Gender']=='Female')].value_counts()
        misc_male = df_patients['Gender'].loc[(df_patients['PATIENT HAD TYPHUS?']=='No')&(df_patients['Gender']=='Male')].value_counts()
        misc_female = df_patients['Gender'].loc[(df_patients['PATIENT HAD TYPHUS?']=='No')&(df_patients['Gender']=='Female')].value_counts()
    
    if (len(df_patients[column].unique()) == 2) and (column != 'Gender'):
        typhus_yes = df_patients[column].loc[(df_patients['PATIENT HAD TYPHUS?']=='Yes')&(df_patients[column]=='Yes')].value_counts().to_list()
        misc_yes = df_patients[column].loc[(df_patients['PATIENT HAD TYPHUS?']=='No')&(df_patients[column]=='Yes')].value_counts().to_list()
        
        if len(typhus_yes) == 0:
            typhus_yes = [0]
        if len(misc_yes) == 0:
            misc_yes = [0]
        else:
            typhus_yes = typhus_yes[0]
            misc_yes = misc_yes[0]
    
    if len(df_patients[column].unique()) > 2:
        typhus_median = df_patients[column].loc[df_patients['PATIENT HAD TYPHUS?']=='Yes'].median()
        typhus_iqr1 = df_patients[column].loc[df_patients['PATIENT HAD TYPHUS?']=='Yes'].quantile(0.25)
        typhus_iqr3 = df_patients[column].loc[df_patients['PATIENT HAD TYPHUS?']=='Yes'].quantile(0.75)
        misc_median = df_patients[column].loc[df_patients['PATIENT HAD TYPHUS?']=='No'].median()
        misc_iqr1 = df_patients[column].loc[df_patients['PATIENT HAD TYPHUS?']=='No'].quantile(0.25)
        misc_iqr3 = df_patients[column].loc[df_patients['PATIENT HAD TYPHUS?']=='No'].quantile(0.75)
    
    try:
        misc_male = float(misc_male)
        misc_female = float(misc_female)
        misc_yes = misc_yes
        typhus_male = float(typhus_male)
        typhus_female = float(typhus_female)
        typhus_yes = typhus_yes
        
    except:
        pass
    
    dictionaryM = {'Feature': feature_misc,
                   'Male': misc_male,
                   'Female': misc_female,
                   'Median': misc_median,
                   'IQR1': misc_iqr1,
                   'IQR3': misc_iqr3,
                   'Yes': misc_yes}
    
    dictionaryT = {'Feature': feature_typhus,
                  'Male': typhus_male,
                  'Female': typhus_female,
                  'Median': typhus_median,
                  'IQR1': typhus_iqr1,
                  'IQR3': typhus_iqr3,
                  'Yes': typhus_yes}
    
    df_analysis = df_analysis.append(dictionaryM, ignore_index=True)
    df_analysis = df_analysis.append(dictionaryT, ignore_index=True)

In [12]:
df_analysis

,Feature,Male,Female,Median,IQR1,IQR3,Yes
0,Age (years) - MIS-C,NaN,NaN,9.000,5.0000,12.00000,NaN
1,Age (years) - Typhus,NaN,NaN,12.000,9.0000,15.00000,NaN
2,Gender - MIS-C,77.0,56.0,NaN,NaN,NaN,NaN
3,Gender - Typhus,43.0,44.0,NaN,NaN,NaN,NaN
4,Epidemiologic link to SARS-CoV-2 - MIS-C,NaN,NaN,NaN,NaN,NaN,91.0
5,Epidemiologic link to SARS-CoV-2 - Typhus,NaN,NaN,NaN,NaN,NaN,15.0
6,FEVER fever before hospital - MIS-C,NaN,NaN,5.000,4.0000,6.00000,NaN
7,FEVER fever before hospital - Typhus,NaN,NaN,7.000,6.0750,9.00000,NaN
8,FEVER Tmax xxx or greater until next degree -...,NaN,NaN,103.500,103.0000,104.00000,NaN
9,FEVER Tmax xxx or greater until next degree -...,NaN,NaN,103.000,102.0000,103.00000,NaN
10,Lowest systolic BP in ED (within first two hou...,NaN,NaN,96.000,82.5000,107.00000,NaN
11,Lowest systolic BP in ED (within first two hou...,NaN,NaN,108.000,99.0000,115.50000,NaN
12,Lowest diastolic BP in ED (within first two ho...,NaN,NaN,53.000,43.0000,59.00000,NaN
13,Lowest diastolic BP in ED (within first two ho...,NaN,NaN,58.000,54.0000,65.50000,NaN
14,Highest heart rate in ED (within first two hou...,NaN,NaN,135.000,120.0000,146.50000,NaN
15,Highest heart rate in ED (within first two hou...,NaN,NaN,113.000,102.5000,127.00000,NaN
16,Antecedent Illness - MIS-C,NaN,NaN,NaN,NaN,NaN,51.0
17,Antecedent Illness - Typhus,NaN,NaN,NaN,NaN,NaN,6.0
18,Conjunctivitis - MIS-C,NaN,NaN,NaN,NaN,NaN,96.0
19,Conjunctivitis - Typhus,NaN,NaN,NaN,NaN,NaN,34.0
20,Rash - MIS-C,NaN,NaN,NaN,NaN,NaN,68.0
21,Rash - Typhus,NaN,NaN,NaN,NaN,NaN,70.0
22,Adenopathy - MIS-C,NaN,NaN,NaN,NaN,NaN,9.0
23,Adenopathy - Typhus,NaN,NaN,NaN,NaN,NaN,12.0
24,"Mucosal changes (Strawberry tongue, cracking l...",NaN,NaN,NaN,NaN,NaN,38.0
25,"Mucosal changes (Strawberry tongue, cracking l...",NaN,NaN,NaN,NaN,NaN,13.0
26,Hand/foot edema - MIS-C,NaN,NaN,NaN,NaN,NaN,13.0
27,Hand/foot edema - Typhus,NaN,NaN,NaN,NaN,NaN,0.0
28,"GI involvement (nausea/vomiting, abdominal pai...",NaN,NaN,NaN,NaN,NaN,123.0
29,"GI involvement (nausea/vomiting, abdominal pai...",NaN,NaN,NaN,NaN,NaN,65.0
30,"Neuro involvement (AMS, headache, encepalopath...",NaN,NaN,NaN,NaN,NaN,75.0
31,"Neuro involvement (AMS, headache, encepalopath...",NaN,NaN,NaN,NaN,NaN,58.0
32,"MSK involvement (arthralgias, arthritis, myalg...",NaN,NaN,NaN,NaN,NaN,49.0
33,"MSK involvement (arthralgias, arthritis, myalg...",NaN,NaN,NaN,NaN,NaN,51.0
34,"Respiratory involvement (tachypnea, respirator...",NaN,NaN,NaN,NaN,NaN,47.0
35,"Respiratory involvement (tachypnea, respirator...",NaN,NaN,NaN,NaN,NaN,33.0
36,"Cardiac involvement (chest pain, arrhythmia) -...",NaN,NaN,NaN,NaN,NaN,14.0
37,"Cardiac involvement (chest pain, arrhythmia) -...",NaN,NaN,NaN,NaN,NaN,8.0
38,"WBC, admission - MIS-C",NaN,NaN,9.415,7.1875,12.42000,NaN
39,"WBC, admission - Typhus",NaN,NaN,7.300,5.8075,9.36500,NaN
40,"ALC, admission - MIS-C",NaN,NaN,0.965,0.6600,1.66500,NaN
41,"ALC, admission - Typhus",NaN,NaN,1.925,1.1175,2.72000,NaN
42,"ANC, admission - MIS-C",NaN,NaN,7.390,5.0150,10.29000,NaN
43,"ANC, admission - Typhus",NaN,NaN,4.725,3.4025,6.23250,NaN
44,"Platelets, admission - MIS-C",NaN,NaN,155.000,117.2500,205.50000,NaN
45,"Platelets, admission - Typhus",NaN,NaN,161.000,120.0000,224.00000,NaN
46,"AST, admission - MIS-C",NaN,NaN,52.000,38.0000,77.25000,NaN
47,"AST, admission - Typhus",NaN,NaN,121.000,78.0000,191.75000,NaN
48,"ALT, admission - MIS-C",NaN,NaN,37.000,22.0000,56.00000,NaN
49,"ALT, admission - Typhus",NaN,NaN,80.000,53.0000,137.00000,NaN
50,"Sodium, admission - MIS-C",NaN,NaN,133.000,130.0000,135.00000,NaN
51,"Sodium, admission - Typhus",NaN,NaN,135.000,133.0000,137.00000,NaN
52,"Troponin, admission - MIS-C",NaN,NaN,0.046,0.0100,0.20100,NaN
53,"Troponin, admission - Typhus",NaN,NaN,0.010,0.0100,0.01375,NaN
54,"BNP, admission - MIS-C",NaN,NaN,167.000,40.6000,560.00000,NaN
55,"BNP, admission - Typhus",NaN,NaN,11.950,10.0000,26.22500,NaN
56,"Fibrinogen, admission - MIS-C",NaN,NaN,563.000,490.0000,646.50000,NaN
57,"Fibrinogen, admission - Typhus",NaN,NaN,394.000,322.0000,448.00000,NaN
58,LDH - MIS-C,NaN,NaN,367.000,270.0000,684.00000,NaN
59,LDH - Typhus,NaN,NaN,925.000,572.5000,1496.50000,NaN

In [13]:
df_analysis.to_excel('ai-met-analysis.xlsx')